services:
  fastapi:
    build:
      context: ./server
    ports:
      - "8001:8000"
    env_file:
      - "./server/.env"
    depends_on:
      - mongo

  nextjs:
    build:
      context: ./client
    ports:
      - "3001:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

